# Generated by Django 6.0.3 on 2026-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
