# Generated by Django 6.0.3 on 2026-04-02 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
